### ISSUE TITLE
Java Conventions

### ISSUE THREAD

**Issue by deeprobin** [LeshDev/RoleBotPlus#3]
1. I saw some package names starting with a capital letter. 
This is not recommended by java conventions.
Correction-Example: GuildEvent -> guildEvents

2. But your class names are also not recommended.
Correction-Example: ban -> BanEvent

**Comment by deeprobin** [comment]
Here a little attachment for the naming conventions: http://www.oracle.com/technetwork/java/codeconventions-135099.html

**Comment by Sanduhr32** [comment]
You may link files and do a pull request. However its true. I may do this if nobody else does.

**Comment by derLesh** [comment]
Changed all classes to their original name
